[webservers]
132.196.69.247 ansible_user=azureuser ansible_password=Dashboard@2026! ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Replace <YOUR_VM_PUBLIC_IP> with the IP from terraform output
