[webservers]
${VM_PUBLIC_IP} ansible_user=azureuser ansible_password={{ vm_password }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
${VM_SNOOZED_IP} ansible_user=azureuser ansible_password={{ vm_password }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
${VM_DESTROYED_IP} ansible_user=azureuser ansible_password={{ vm_password }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[vm_running]
${VM_PUBLIC_IP} ansible_user=azureuser ansible_password={{ vm_password }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[vm_snoozed]
${VM_SNOOZED_IP} ansible_user=azureuser ansible_password={{ vm_password }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[vm_destroyed]
${VM_DESTROYED_IP} ansible_user=azureuser ansible_password={{ vm_password }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'